// Hotels Database
const hotelsData = [
  {
    id: 1,
    name: "Grand Palace Hotel",
    location: "Astana, Kazakhstan",
    city: "Astana",
    price: 15000,
    rating: 4.8,
    image: "assets/hotel1.jpg",
    amenities: [
      "Free WiFi",
      "Pool",
      "Spa",
      "Restaurant",
      "Gym",
      "24/7 Service",
    ],
    description:
      "Luxury 5-star hotel in the heart of Astana with stunning city views and world-class amenities.",
    rooms: 150,
    checkInTime: "14:00",
    checkOutTime: "12:00",
  },
  {
    id: 2,
    name: "Silk Road Resort",
    location: "Almaty, Kazakhstan",
    city: "Almaty",
    price: 12000,
    rating: 4.6,
    image: "assets/hotel2.jpg",
    amenities: ["Free WiFi", "Mountain View", "Breakfast", "Parking", "Hiking"],
    description:
      "Beautiful resort with breathtaking mountain views and modern amenities.",
    rooms: 120,
    checkInTime: "15:00",
    checkOutTime: "11:00",
  },
  {
    id: 3,
    name: "Ocean Breeze Hotel",
    location: "Aktau, Kazakhstan",
    city: "Aktau",
    price: 10000,
    rating: 4.5,
    image: "assets/hotel3.jpg",
    amenities: ["Beach Access", "Pool", "Bar", "Water Sports", "WiFi"],
    description:
      "Beachfront hotel perfect for relaxation and water activities.",
    rooms: 80,
    checkInTime: "14:00",
    checkOutTime: "12:00",
  },
  {
    id: 4,
    name: "Business Elite Hotel",
    location: "Astana, Kazakhstan",
    city: "Astana",
    price: 18000,
    rating: 4.9,
    image: "assets/hotel4.jpg",
    amenities: [
      "Conference Rooms",
      "Business Center",
      "Gym",
      "Restaurant",
      "WiFi",
    ],
    description: "Premium business hotel with state-of-the-art facilities.",
    rooms: 200,
    checkInTime: "13:00",
    checkOutTime: "12:00",
  },
  {
    id: 5,
    name: "Cozy Inn",
    location: "Shymkent, Kazakhstan",
    city: "Shymkent",
    price: 8000,
    rating: 4.3,
    image: "assets/hotel5.jpg",
    amenities: ["Free WiFi", "Parking", "Breakfast", "24h Reception"],
    description: "Comfortable budget-friendly hotel for travelers.",
    rooms: 60,
    checkInTime: "14:00",
    checkOutTime: "11:00",
  },
  {
    id: 6,
    name: "Mountain View Lodge",
    location: "Almaty, Kazakhstan",
    city: "Almaty",
    price: 13000,
    rating: 4.7,
    image: "assets/hotel6.jpg",
    amenities: ["Hiking Tours", "Restaurant", "Spa", "WiFi", "Mountain Guides"],
    description:
      "Perfect retreat for nature lovers with spectacular mountain scenery.",
    rooms: 90,
    checkInTime: "15:00",
    checkOutTime: "12:00",
  },
];

// City coordinates for weather API
const cityCoordinates = {
  Astana: { lat: 51.1694, lon: 71.4491 },
  Almaty: { lat: 43.222, lon: 76.8512 },
  Aktau: { lat: 43.6508, lon: 51.1725 },
  Shymkent: { lat: 42.3417, lon: 69.5901 },
};
